services:
  - type: web
    name: python-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        value: "mysql://user:password@hostname/dbname"
